import { memo } from 'react'

// Pre-generated by `npm run generate-audio` (ElevenLabs text-to-speech).
function play(value: number) {
  new Audio(`${import.meta.env.BASE_URL}audio/${value}.mp3`).play()
}

const Card = memo(({ value, spanish, isRevealed, onReveal }: {
  value: number
  spanish: string
  isRevealed: boolean
  onReveal: (value: number) => void
}) => (
  <div className={`card ${isRevealed ? 'revealed' : ''}`}>
    <span className="numeral">{value}</span>
    <span className="word">{isRevealed ? spanish : '?'}</span>
    <div className="card-actions">
      <button className="listen-btn" onClick={() => play(value)} aria-label={`Listen to ${value}`}>🔊</button>
      {!isRevealed && (
        <button className="reveal-btn" onClick={() => onReveal(value)}>hint</button>
      )}
    </div>
  </div>
))

export default Card
